# Generated by Django 6.0.3 on 2026-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dumanity_webhooks_receiver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deadletter",
            name="replay_event_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deadletter",
            name="replay_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deadletter",
            name="replayed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
