# Generated by Django 6.0.3 on 2026-04-04 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre lógico del endpoint', max_length=100)),
                ('url', models.URLField(help_text='URL destino')),
                ('secret', models.CharField(help_text='Secret HMAC', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('payload', models.JSONField(help_text='Evento completo')),
                ('attempts', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.webhookendpoint')),
            ],
        ),
    ]
